---
title: ""
author: ""
date: ""
output:
  html_document:
    includes:
      before_body: ../header.shtml
    css: ../styles/rpruim2017.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Test Information

### Test 1 

**Date:** Wed, February 28

**Material Covered**: Graphs (Rosen chapter 9.1-9.5, 9.7) and Counting (Rosen 5.1-5.4)

#### Topics

**Graphs:** 
modeling with graphs (what do edges and vertices represent?);
types of graphs(directed, undirected, self-loops, etc., etc.);
graph terminology (examples: vertex, edge, adjacent, degree, bipartite, path, connected);
graph representations (adjacency matrix, incidence matrix, edge list, adjacency list);
graph isomorphism; graph invariants;
Euler paths and circuits; Hamilton paths and circuits; 
planar graphs; Euler's formula; Kuratowski's Theorem

**Counting:** 
bijection principle; multiplication principle; 
addition principle;  division principle; 
inclusion-exclusion; pigeonhole principle; 
permutations and combinations; binomial coefficients.


### Test 2 

**Date:** Wed, April 4

**Material Covered**: Counting and Probability (Rosen 5 and 6)

#### Topics

**Counting:** 
Bijection principle (no double counting, no skipping);
multiplication principle; 
addition principle;  division principle; 
inclusion-exclusion; pigeonhole principle; 
permutations and combinations; binomial coefficients.
Table 1 on page 375;
inclusion-exclusion.

**Probability:**
Definition of finite probability and applications involving counting problems; 
empirical vs theoretical probability;
3 probability axioms;
complement rule; 
equally likely rule;
union rule;
conditional probability;
indepedence; 
Bayes probability (e.g., false positives and false negatives);
probability trees;
random variables;
expected value of a random variable;
variance of a random variable.


### Test 3 

**Date:** Wed, May 2

**Material Covered**: Languages, Grammars, and Automata
(Rosen 12.1 -- 12.4)

#### Topics

**Grammars:** components of a grammar (terminals, nonterminals, start symbol,
production rules, etc.), derivations, language generated by a grammar, types of
grammars (regular, context sensitive, context free).

**Automata:** components of an automaton (input alphabet, states, start state,
final states, transition funciton), DFA, NFA, GNFA, language recognized by 
an automaton, building up a complex automaton from component
automata.

**Regular expressions:** notation, 3 base cases and three operations, language
represented by a regular expression.

**Regular languages:** Equivalence of regular expressions, regular grammars,
DFAs, and NFAs.  (You should know how to do all of the conversions we have
learned.)  Pumping Lemma and showing languages are not regular.

