project:
  type: book
  preview:
    port: 5252
  resources:
    - from-class

book:
  downloads: pdf
  title: "Worksheets for Math 252"
  author: "Randall Pruim"
  date: last-modified
  date-format: YYYY/mm/dd HH:mm
  chapters:
    - index.qmd
    - part: "Graphs"
      chapters:
        - graphs/01-Graphs-Intro.qmd
        - graphs/02-Graphs02.qmd
        - graphs/03-Graphs-Representations.qmd
        - graphs/04-Graph-Isomorphism.qmd
        - graphs/05-Graphs-Paths.qmd
        - graphs/06-Graphs-Bipartite-Planar.qmd
#        - graphs/07-Graphs-Euler.qmd
    - part: "Counting and Probability"
      chapters:
        - counting-and-probability/01-counting-basic.qmd
        - counting-and-probability/02-counting-pigeonhole.qmd
        - counting-and-probability/03-counting-division.qmd
        - counting-and-probability/04-counting-donuts.qmd
        - counting-and-probability/05-probability.qmd
        - counting-and-probability/06-probability-conditional.qmd
        - counting-and-probability/07-probability-conditional2.qmd
        - counting-and-probability/08-probability-bayes.qmd
        - counting-and-probability/09-random-variables.qmd
        - counting-and-probability/10-expected-value.qmd
        - counting-and-probability/11-E-is-linear.qmd
        # - counting-and-probability/12-variance.qmd

format:
  pdf:
    documentclass: scrreprt
    fontsize: 10pt
    include-before-body: before_body.tex
    include-in-header:
      - preample.tex
      - macros.tex
    toc-depth: 2
    fig-pos: 'h'
    geometry:
      - "margin = 0.7in"
      - "top = 0.5in"
      - "bottom = 0.9in"
  html:
    theme: cosmo
    include-before-body: macros.tex
