---
output: 
  html_document:
    includes:
      before_body: ../../header.shtml
    css: ['../../../styles/rpruim2017a.css', '../../../styles/folding.css']
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\def\prob{p}
\def\Prob{p}
\def\intersect{\cap}
\def\union{\cup}
\def\To{\Rightarrow}


<script src="../../../styles/folding.js"></script>

### Daily Dope Sheet 

## Friday, April 3: Alphabets, Languages, and Grammars

#### Homework 

#### Stuff to do


#### Comments/Hints/Solutions

\def\emptystring{\lambda}

<div class = "explain" label = "Exercise 1.1">
$V^0$ is the set of all words/strings with exactly 0 symbols.  The only one of these is the 
empty string $\emptystring$, so $V^0 = \{ \emptystring \}$.

$V^2$ is the set of all words/strings with exactly 2 symbols.  The symbols must be either 0 or 1,
so we get 
$V^2 = \{00, 01, 10, 11 \}$.

$V^{*}$ is te set of all binary strings of any length. (This is an infinite set
-- countably infinite, for those of you who know what countable means.)
</div>

<div class = "explain" label = "Exercise 1.2">
$V^0$ is the set of all words/strings with exactly 0 symbols.  The only one of
these is the empty string $\emptystring$, so $V^0 = \{ \emptystring \}$. (You might 
be realizing the $V^0$ is the same no matter what $V$ is -- if so, you are correct.)

$V^2$ is the set of all words/strings with exactly 2 symbols.  The symbols must 2's, 
so we get  $V^2 = \{22 \}$.

$V^{*}$ is te set of all strings of any length that consist entirely of 2's. 
(This is an infinite set -- countably infinite, for those of you who know what 
countable means.)
</div>


<div class = "explain" label = "Exercise 1.3">
It cannot be an alphabet because the definition says alphabets must be non-empty.

$\emptyset$ *could* be used as a letter, in which case it would also be a word of length 1.
We won't usually do this, however, since it gets confusing.

$\emptyset$ is a subset of $\V^{*}$ no matter what $V$ is, so it is a language.
</div>

<div class = "explain" label = "Exercise 1.4">
Here's one way to do it (the numbers indicate which rule is being used):

$$
ABa \stackrel{3}{\To} Aaba \stackrel{2}{\To} BBaba 
\stackrel{3}\To Bababa \stackrel{3}{\To} abababa
$$

</div>

<div class = "explain" label = "Exercise 1.5">
To be in the language of the grammar, we must be able to start with 
the start symbol and apply rules until we get to the target string.
We just did most of this in the preceding problem.

$$S\stackrel{1}{\To} ABa \stackrel*{\To} abababa$$
So $abababa$ is in the language generated by $G_1$.
</div>

<div class = "explain" label = "Exercise 1.6">
Start by generating a few strings.  You don't have very many 
rules, so you won't have a lot of choice.  After a little experimenting,
you should be able to describe which strings are possible to derive and which
ones are not.

It is fine to describe the language using words -- but they must be precise
enough to know exactly which things are in and out of the language.
</div>

<div class = "explain" label = "Exercise 1.7">
Hints:

* Why must the second rule be used *exactly* one time?
* What does that tell you about any string generated?
* What happens each time the first rule is used?

</div>

<div class = "explain" label = "Exercise 1.8">
$G_4$ is more complicated, so it would be challenging to figure out 
exactly what can and cannot be generated. But you should be able 
to generate examples.  

***Note:** it is easy to convince someone that a
string is in a language -- you just show how to derive it using the rules.
It is harder to convince someone that a string is *not* in the language --
you need a convincing argument that there is *no way* to derive it using 
the rules. This sort of assymetry show up in many interesting computer
science problems, including the famous P vs NP problem.

Here is an example derivation:

$$
S \To AB \To CaB \To baB \To baCb \To bacbb
$$

You should be able to find several others.
</div>

<div class = "explain" label = "Exercise 1.9">
Note: You need to have the same number of 0s and 1s, and the 0s must 
all come before the 1s.
</div>

<div class = "explain" label = "Exercise 1.10">
The difference between this example and the previous one is that here 
you must have at least one 0 (and at least one 1).
</div>

<div class = "explain" label = "Exercise 1.11">
How is the different from the previous two examples?
Note $\mathbb{N} = \{0, 1, 2, 3, \dots \}$.  (Think unsigned integer -- but
without a MAXINT.)

</div>

<br><br>