---
output: 
  html_document:
    includes:
      before_body: ../../header.shtml
    css: ../../../styles/rpruim2017a.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\def\prob{p}
\def\intersect{\cap}
\def\union{\cup}

<style>
button.collapsible {
  background-color: #777;
  color: white;
  cursor: pointer;
  padding: 4px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.active, button.collapsible:hover {
  background-color: #555;
}

.content {
  padding: 0 9px;
  display: none; 
  overflow: hidden;
  background-color: #f1f1f1;
}
</style>

### Daily Dope Sheet 

## Wednesday, March 18



#### Homework 

  * due today: WW07
  * due Wednesday: WW08 and PS 9

#### Stuff to do

1. Get today's worksheet (section 7). 

    * [PDF](../counting-and-probability/Counting-and-Probability.pdf) 
    * [HTML](../counting-and-probability/probability-trees-and-bayes.html)

2. Focus your attention on sections 1 - 3. (We will look at sections 4 and 5 on Friday.)

    a. Bob's boxes
    b. Breast cancer screening
    b. Disease testing 
    
    There are some comments/hints/solutions below. Take a look at them after
    each section before moving on to the next.
    

#### Comments/Hints/Solutions

Check our MS Team channels as well.

<button type = 'button' class = "collapsible">Bob's Beautiful Boxes</button>
<div class = "content">
</div>


<button type = 'button' class = "collapsible">Breast Cancer Screaning</button>
<div class = "content">
</div>


<button type = 'button' class = "collapsible">Disease Testing</button>
<div class = "content">
</div>



<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>