---
output: 
  html_document:
    includes:
      before_body: ../../header.shtml
    css: ../../../styles/rpruim2017a.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\def\prob{p}
\def\intersect{\cap}
\def\union{\cup}


### Daily Dope Sheet 

## Friday, March 20

#### Homework 

  * due today: WW08 and PS 9
  * due Monday, March 30: TBD

#### Stuff to do

1. Get today's worksheets. We'll be working section 7 and the beginning of section 8. 

    * [PDF](../counting-and-probability/Counting-and-Probability.pdf) 
    * [HTML -- section 7](../counting-and-probability/probability-trees-and-bayes.html)
    * [HTML -- section 8](../counting-and-probability/random-variables.html)

2. Section  7.5: Disease Testing

3. Section  7.6: Hashing
    
    There are some comments/hints/solutions below. Take a look at them after
    each section before moving on to the next.

4. Sections 8.1 and 8.2: Introduction to Random Variables


#### Comments/Hints/Solutions

Check our MS Team channels as well.


<button type = 'button' class = "collapsible">Random Primality Testing</button>
<div class = "content">

a. Since $n$ is prime, `MillersTest(n, b)` will never say "composite", so the `PrimeTest(n)` will
always return "prime (well, probably)".  

b. At each pass through the loop, the probability of `MillersTest(n, b)` returning "composite"
is greater than 3/4, so the probability of continuing to the next pass through the loop is 
less than 1/4.  The probability of doing this 5 times is $(1/4)^5 \approx `r round(0.25^5, 5)`$.

Read more about this problem on page 464.
</div>

<button type = 'button' class = "collapsible">Hashing</button>
<div class = "content">
Read about this problem on page 462.
</div>


<button type = 'button' class = "collapsible">Exercise 8.2.1</button>
<div class = "content">
The must sum to 1. The probabilities of all possibilities must always sum to 1.
</div>


<button type = 'button' class = "collapsible">Exercise 8.2.2</button>
<div class = "content">
$p(X = 2) = 0.3$
</div>


<button type = 'button' class = "collapsible">Exercise 8.2.3</button>
<div class = "content">
$p(X > 2) = p(X = 3) + p(X = 4) = 0.2 + 0.1 = 0.3$
</div>

<button type = 'button' class = "collapsible">Exercise 8.2.4</button>
<div class = "content">
$p(X = 2) + p(X = 4) = 0.3 + 0.1 = 0.4$
</div>

<button type = 'button' class = "collapsible">Exercise 8.2.5</button>
<div class = "content">
The possible values are 0, 1, 2, 3, or 4.  (Don't forget 0.)

$p(X = 2) = \binom{4}{2} 0.5^4 = `r choose(4,2) * 0.5^4`$  (Why $\binom{4}{2}$?)

You should be able to work out the other four probabilities.  Be sure they sum to 1.
</div>

<button type = 'button' class = "collapsible">Exercise 8.2.6</button>
<div class = "content">
The possible values are 0, 1, 2, and 3.

There are only 16 possible die rolls. There are two ways you could approach this.

* For each of the 16, determine what the value of $X$ will be.
* For each possible value, ask yourself how many of the 16 rolls give you that value.

</div>

<button type = 'button' class = "collapsible">Exercise 8.2.7</button>
<div class = "content">

Some hints:

* Your probabilities should sum to 1.
* Make sure that you are always creating a full 5-card hand.
* It is probably easiest to work with [unordered hands](ordered-vs-unordered-hands.mp4).
* There are only 4 diamonds in the deck, so the largest number of diamonds you can have in your 
hand is 4.

</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>