
# Division Principle

```{r setup-division, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A problem about cookies

1. Suppose 100 cookies are distributed equally to a group of kids.
Each kid receives 4 cookies. How many kids are there?
 
## Division and other Principles

The reasoning used to solve the previous problem is called the **division principle**:

> If you count each item the same number of times, you can divide the total count by the 
number of times each item is counted to get the number of items.  

<!-- We have actually seen this before: -->

<!-- 2. If the total degree of a graph is 58, how many edges does it have? -->

<!-- When we count the degrees, we count each edge twice, so there are $\frac{58}{2} = 29$  -->
<!-- edges in the graph. -->

2. Express similar principles for addition, subtraction, and multiplication.

<!-- Multiplication: -->
<!-- If a task can be broken up into two consecutive steps. If  -->
<!-- step 1 can be performed in $m$ ways,  -->
<!-- and for each of these, step 2 can be performed in $n$ ways,  -->
<!-- then the task itself can be performed in $m n$ ways. -->


## More Counting Problems

Here are some additional problems that involve our counting principles, including the 
division principle. As you work through them, identify where you are using which principle.


3. An NBA basketball team has 12 players.  
  
    a. How many ways can the coach select the five players to start the game?  (Positions
    don't matter.)
    
    b. How many ways can the coach select one player to be center, two to be forwards, and two to 
    be guards?  (That is, the positions matter, but any player may play any position.)
    
    c. Now suppose the team has 3 centers, 5 forwards and 4 guards.  How many ways can the 
    coach select one of the centers, two of the forwards, and two of the guards? 
    
4. How many 5-card poker hands can be dealt from a standard 52-card deck?

5. How many 5-card poker hands include at least one card from each suit?  (There are 4 suits: clubs, diamonds, hearts, and spades.  Each suit has 13 cards.)
  
6. How many bit strings of length 8 have exactly three 1's?
  
7. How many "words" can you make with the letters in MISSISSIPPI?  (The "words" 
  do not need to be real words -- just sequences of letters.)
  
8. A class of 20 gets into groups of 4 to work on some problems. 
  
    a. How many such groups of 4 are there?
  
    b. You get to work with 3 other people. How many such groups of 3 are there?
    
    c. How many different ways can the class be put into 5 groups of 4? How does this question
    differ from part a?

9. How many bit strings of length 10 contain either five consecutive 0s 
or five consecutive 1s?

<!-- 9. How many bit strings of length eight contain either three consecutive  -->
<!-- 0s or four consecutive 1s?  -->
  
  
 

