

# Random Variables
 
## Describing Random Variables

A **random variable** is a random process that produces a number.  

  * Typically, capital letters (often near the end of the alphabet) are used for
  random variables.  Example:
  
 $$ 
    \Prob(X = 3) = 0.2
 $$
 
  * We will focus our attention on discrete random variables.  A discrete random 
  variable can only take on values from a finite or countable list of values. We will
  be especially interested in the finite case.

  * Any random process can  be converted into a random variable by a function
  that maps outcomes in the sample space to numbers. In our text you will see
  notation like $X: S \to R$ (X maps each outcome to a number) or $X(HHT) = 2$
  (counting the number of heads).
  
  * We will mostly work with random variables in two formats: (a) a table of
  values and probabilities, or (b) a formula that tells how to compute the
  probability for any specified value.
  
## Probability Tables

<!-- ### First example {-} -->

When studying random variables, we typically want to now the answers to two questions:

* What values can the random variable have?
* With what probability does it have each of those values?

We can create a **probability table** as a way to record the answers to those two 
questions. Here is an example probability table for a random variable we'll call $X$.

value       |  1   |   2   |  3   |   4  
----------: | :--: | :---: | :--: | :--:
probability | 0.4  |  0.3  | 0.2  | 0.1

1. What properties must the probabilities in such a table always have?

2. What is $\Prob(X = 2)$?

3. What is $\Prob(X > 2)$?

4. What is $\Prob(X \mbox{ is even})$?

<!-- ### Creating a probability table {-} -->

---

5. Create a probability table for the random variable $H$, where $H$ is the number 
of heads observed when flipping 4 fair coins.  Start by determining all the possible values.
Then for each value, determine its probability.

6. Let $X$ be the absolute value of the difference in the values of two fair 4-sided dice.
For example, if you roll a 3 and a 1, the difference is 2.
Create a probability table for $X$.  (What are the possible values?)

7. Let $D$ be the number of diamonds dealt in a 5 card hand.  

    a. Create a probability table for $D$.
    
    b. What is the most likely number of diamonds in such a hand?


## Probability Functions

We can also describe random variables with formulas.

8. Let $Y$ be defined by $\Prob(Y = y) = y/10$ when $y \in \{1, 2, 3, 4\}$.

    a. What is $\Prob(Y = 3)$?
  
    b. Create a probability table for $Y$.

  
9. Suppose you keep flipping a coin until you get a head.  Let $F$ count the number of flips.

    a. What is $\Prob(F = 1)$?
  
    b. What is $\Prob(F = 2)$?
  
    c. What is $\Prob(F = 3)$?
  
    d. What are the possible values for $F$?
  
    e. Can you come up with a formula for $\Prob(F = k)$?

10. Let $X$ be the number of heads in $n$ tosses of a fair coin.

    a. What are the possible values of $X$?
  
    b. Give a formula for $\Prob(X = k)$?
  
    c. Give a formula for $\Prob(X = x)$?  (This is the same as the preceding part, but with different notation.)
  
11. Now suppose the coin isn't fair.  Let $p$ be the probability of getting a head on each flip.
Let $X$ be the number of heads in $n$ flips.

    a. What is $\Prob(X=1)$ when $n = 1$ and $p = 0.75$?
  
    a. What is $\Prob(X=1)$ when $n = 2$ and $p = 0.75$?
  
    c. Make a probability table for $X$ when $n = 3$ and $p = 0.75$.
  
    b. Determine a general formula for $\Prob(X = x)$ in terms of $n$ and $p$.
  
## Binomial Distributions

The previous example illustrates a scenario that arises in many applications:

 1. A random process consists for $n$ parts or steps (traditionally called trials).
 2. Each trial has two possible outcomes (traditionally called success and failure).
 3. The probability of success is the same ($p$) for each trial.
 4. The trials are independent of each other.
 5. Our random variable is the count of the number of successes in the $n$ trials.
 
We will denote this $X \sim \Binom(n,p)$.

12. Create a probability table for a $\Binom(2, 0.2)$ random variable.  

13. Create a probability table for a $\Binom(3, 1/4)$ random variable.
