
# Division Principle

```{r setup-division, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A problem about cookies

1. Suppose 100 cookies are distributed equally to a group of kids.
Each kid receives 4 cookies. How many kids are there?
 
## The Division Principle

The reasoning used to solve the previous problem is called the division principle:
If you count each item the same number of times, you can divide the count by the 
number of times each item is counted to get the number of items.  

We have actually seen this before:

2. If the total degree of a graph is 58, how many edges does it have?
  
When we count the degrees, we count each edge twice, so there are $\frac{58}{2} = 29$ 
edges in the graph.

## More Counting Problems

Here are some additional problems that involve our counting principles, including the 
division principle.

3. An NBA basketball team has 12 players.  
  
    a. How many ways can the coach select the five players to start the game?  (Positions
    don't matter.)
    
    b. How many ways can the coach select one center, two forwards, and two guards?  (That is, the positions matter.)
    
    
4. How many 5-card poker hands can be dealt from a standard 52-card deck?
  
5. A class of 36 gets into groups of 4 to work on some problems. 
  
    a. How many such groups of 4 are there?
  
    b. You get to work with 3 other people. How many such groups of 3 are there?
 
6. How many bit strings of length 8 have exactly three 1's?
  
7. How many "words" can you make with the letters in MISSISSIPPI?  (The "words" 
  do not need to be real words.)
  
\newpage  
  
  
  
  
 

