
# Probability


<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->

## Notation Note

The notation used to probability varies a bit from book to book.  Three common notations for the probability
of an event $E$ are $p(E)$, $\mathrm{P}(E)$ and $\mathrm{Pr}(E)$.  Our book uses the lower case $p()$.

## Probability Axioms

These three statements are the foundation of probability. Anything that follows these 
rules is a probability.

1. For any event $E$, $0 \le \Prob(E) \le 1$.
 
2. If $S$ is the sample space, then $\Prob(S) = 1$.
 
3. The probability of a disjoint union is the sum of the probabilities.
 
    a. $\Prob(A \union B) = \Prob(A) + \Prob(B)$, if $A \intersect B = \emptyset$.
    
    b. $\Prob(A_1 \union A_2 \union \cdots \union A_n) = \Prob(A_1) + \Prob(A_2) + \cdots + \Prob(A_n)$, 
    if $A_i \intersect A_j = \emptyset$ whenever $i \neq j$.
    
    c. $\Prob(\union_{i=1}^\infty A_i ) = \sum_{i = 1}^n \Prob(A_i)$,
    if $A_i \intersect A_j = \emptyset$ whenever $i \neq j$.

## Some Additional Probability Rules

These probability rules also hold for all probabilities.

4. **Complement Rule:** For any event $E$, $\Prob(\overline{E}) = 1 - \Prob(E)$
 
5. **Union Rule:** For any events $A$ and $B$, $\Prob(A \union B) = \Prob(A) + \Prob(B) - \Prob(A \intersect B)$.
 
6. **Equally Likely Rule:** If all outcomes in a sample space are equally likely, then 
 $$
 \Prob(E) = \frac{|E|}{|S|}
 $$
 
## Exercises

1. Show how the Complement Rule follows from the axioms.
 
2. Show how the Union Rule follows from the axioms.

3. Show how the Equally Likely Rule follows from the axioms.

As you do the problems below, explicitly mention each of the 6 probability
axioms/rules as you use them. (If you use the Equally Likely Rule, be sure to
check that the outcomes are indeed equally likely.) For now, don't use any other
rules (if you happen to know more) unless you first prove them using the rules
above.

4. **Urn.** An urn contains 3 red balls and 5 blue balls.  If you randomly
select two balls, what is the probability that both are the same color?
 
5. **Dice.** If you role two standard dice, what is the probability that the sum
of the dice is 5?
 
6. **Smaller Dice.** If you role two 4-sided dice, what is the probability that the sum of the dice is 5?
 
7. **6 or doubles.** If you roll two standard dice, what is the probability that
you get either doubles or a sum equal to 6?
 
8. **Lotto.** Many lotteries offer a game that works like this: The player
selects three digits (0--9). Later the lottery selects three digits.  If the
player's three digits match the lottery-selected three digits in order, the
player wins a large prize.  If the digits match, but not in the correct order,
the player wins a smaller prize.

    a. If you pick the digits 1-2-3, what is your probability of winning the large prize? The small prize?
   
    b. If you pick the digits 6-1-6, what is your probability of winning the large prize? The small prize?
   
    c. What if you pick 7-7-7 (because 7 is your lucky number)?

9. **Flush.** If you are dealt 5 cards from a standard deck, what is the probability that they all have the same suit 
 (clubs, diamonds, hearts, or spades)?
 
10. **4-of-a-kind.** If you are dealt 5 cards from a standard deck, what is the probability that four of them are the same 
 kind?  (By kind we mean a number 2--10, Jack, Queen, King, or Ace.)
 
11. **Random Bit String.** A bitstring of length 8 is selected at random (each bit string is equally likely).
What is the probability that the string has at least one 0?
 
12. **Yahtzee.** In Yahtzee, five standard dice are rolled.  If you roll 5 standard dice, what is the probability that
 
    a. all 5 numbers match? (That's called a Yahtzee).
    
    b. at least two numbers match?  (In the game you get to re-roll some of the numbers, so if you have at
    least two that match, you have something to start from in an attempt to get a Yahtzee in subsequent rolls.)

13. **Loaded Dice.** 
A six-sided die has been "loaded" so that 6 is twice as likely to 
be rolled as any other number.  
 
    a. What is the probability of rolling a 6 with such a die?
    b. What is the probability of rolling doubles with two such dice? (Doubles means two matching numbers.)
    c. What is the probability of rolling doubles with two standard dice?
   
14. **Boys and Girls.** A family has two children.  One of them is a boy.  What is the probability that the other is a girl?
 
15. **More Lottery.** In a lottery game, players select 6 distinct numbers from the numbers 1 -- 40.
 (The order in which they are chosen doesn't matter -- often you select the numbers by punching out
 tabs for the 6 numbers you want and there is no record of the order in which you punched them out.)
 Later, the lottery commission picks 6 numbers.  Compute the probability of each of these events
 and put the results in a nice table.

    a. all 6 numbers match.
    b. exactly 5 of the 6 match.
    b. exactly 4 of the 6 match.
    b. exactly 3 of the 6 match.
    b. exactly 2 of the 6 match.
    b. exactly 1 of the 6 match.
    b. none of the 6 match.
    

\newpage 
 
