---
title: "Counting and Probability"
author: "R Pruim"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::pdf_book: default
  bookdown::gitbook: default
rmd_files: ['index.Rmd',
      "01-Counting-Basic.Rmd",
      "02-Counting-Pigeonhole.Rmd",
      "03-Counting-Division.Rmd",
      "04-Counting-Donuts.Rmd"]
---

```{r skip, eval = FALSE, include = FALSE}
      "05-Probability.Rmd",
      "06-Probability-Conditional.Rmd",
      "07-Probability-Conditional2.Rmd",
      "08-Probability-Bayes.Rmd",
      "09-Random-Variables.Rmd",
      "10-Expected-Value.Rmd",
      "11-E-is-Linear.Rmd",
      "12-Variance.Rmd"]
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggformula)
```

\newpage

# Preface {-}

These exercises were assembled to accompany a Discrete Mathematics course
at Calvin College. 


<!-- Some macros to make mathematics easier -->

\newcommand{\Prob}{operatorname{p}}
\newcommand{\intersect}{\;\cap\;}
\newcommand{\union}{\operatorname{\cup}}
\newcommand{\E}{\operatorname{E}}
\newcommand{\Var}{\operatorname{Var}}
\newcommand{\SD}{\operatorname{SD}}
\newcommand{\Binom}{\textsf{Binom}}


\newpage

