


\documentclass{scrartcl}
\usepackage[margin=.5in,top=.5in,bottom=.3in,includehead,includefoot]{geometry}
\renewcommand{\arraystretch}{1.5}

%\parindent=0pt
\parskip=3pt


%\usepackage{mathpple}
%\usepackage{fullpage}
\usepackage{alltt}
\usepackage{sfsect}
\usepackage{longtable}
\usepackage[yyyymmdd,hhmmss]{datetime}


\def\WW#1{\href{https://mathwebwork.cs.calvin.edu/webwork2/Math252-S18-Pruim/WW#1}{WW#1}}

\newif\ifanswers
\answerstrue
\answersfalse

\def\blank#1{%
\ifanswers
\underline{{\large \sc #1}}
\else
\underline{\phantom{\Large \ \ \ \sc #1 \ \ \ }}
\fi
}

\def\dd#1{\medskip\noindent\textbf{\large #1}}
\def\be{\begin{enumerate}}
\def\ee{\end{enumerate}}
\def\bi{\begin{itemize}}
\def\ei{\end{itemize}}

\def\hwn#1{\relax}
\def\hwn#1{\ {\tiny (#1)}}
\def\hwn#1{$_{\mbox{\ \tiny #1}}$}
\def\hwn#1{~{\tiny #1}}

\usepackage[normalem]{ulem}
\usepackage{ifthen}
\usepackage{fancyhdr}
\usepackage[colorlinks = true, urlcolor = blue]{hyperref}
\include{myabbrev}


\renewcommand{\labelenumi}{\textbf{\arabic{enumi}}}
\newcommand{\myunderline}[1]{\uline{\phantom{Ay}#1\phantom{Ay}}}

\newcommand{\helper}[2][\relax]{(#2)\hwn{#1}}
\newcommand{\extra}[2][\relax]{[#2]\hwn{#1}}
\newcommand{\opt}[2][\relax]{\{#2\}\hwn{#1}}
\newcommand{\mand}[2][\relax]{{\bf \large #2}\hwn{#1}}

\begin{document}


\pagestyle{fancy}

\chead{}
\lhead{Math 252 -- Spring 2018}
\rhead{\thepage/\pageref{end}}
\lfoot{}
\cfoot{Created \today\ --- See web site for most current version.}
\rfoot{}

\begin{center}
  \large
%  Mathematics \& Statistics 156
%
%  Fall 2016
%
\subsection*{Problem Sets Between Test 2 and Test 3}

\end{center}


\textit{Only turn in problems that are \textbf{not} bracketed.}
Bracketed problems are additional problems you can look at.
Round brackets indicate problems that may help you with problems that
are assigned; square brackets are additional problems on material
that you should know, but you are not required to write up solutions;
curly brackets are truly optional and may contain extra nuggets that you
will not be required to know but may be interested in.

Additional assignments will be filled in over time.

\bigskip

\begin{center}

\iftrue

\begin{longtable}{|c|l|}
  \hline
  notation & meaning \\
  \hline
  unbracketed & assigned problem -- turn these in for grading \\
  $()$ & helper/warm-up problem  \\
  $[]$ & additional problems (you are responsible for content, but don't turn them in) \\
  \{\} & covers optional material \\
  \hline
\end{longtable}
\fi

\bigskip


\begin{longtable}{|c|c|c|p{4.3in}|}
  \hline
  Due & Task & Source & Problems \\
  \hline\hline
  \endhead
  Wed 4/11 & PS 9 & Rosen 12.1 &
   \mand[sentences]{1ad}
	 \extra{2}
	 \helper{3}
	 \mand{4}
	 \extra{5}
	 \mand{6a}
	 \mand{9}
	 \helper{13}
	 \mand{14bd}
	 \extra{15}

	 \mand[types of grammars]{19}
	 \mand[palindromes]{20}
	 \mand[union]{21a}
	 % \mand[derivation trees]{24ab}

	 \mand[BNF]{28}
	 \mand[BNF]{31ab}
	 \mand[EBNF]{34}
   \\
	   \hline
	   Fri 4/13 & PS 10 & Rosen 12.3 &
	   \mand[testing strings]{12}
	   \mand[what langauge?]{16--17}
	   \mand[create DFA]{25--26}
   \\
	   \hline

\end{longtable}
\end{center}
\label{end}
\end{document}
\end{document}

