---
pagetitle: M252 | from class
toc-depth: 3
---

# From Class

```{r setup, include = FALSE}
library(tidyverse)
library(mosaic)
```

<script src="styles/folding.js"></script>

<style>
div.indent {
  margin: 0 0 0 25px;
}
</style>


## Worksheets/Handouts

I'll print and bring worksheets to class, but if you lose one or want to have it in
electronic format for some reason, you can get it here as well.

<!-- ### Models of Computation -->

<!-- * Worksheets:  -->
<!--   [PDF](models-of-computation/Models-of-Computation.pdf) -->
<!--   [HTML](models-of-computation) -->

<!-- ### Counting and Probability -->

<!-- * Worksheets:  -->
<!--   [PDF](counting-and-probability/Counting-and-Probability.pdf) -->
<!--   [HTML](counting-and-probability/) -->

:::{.callout-note collapse="true"}
### Before Test 1

::::{.callout-note collapse="true"}
#### Groups starting 9 Jan

```{r echo = FALSE, results = "asis", include = TRUE, message = FALSE}
set.seed(109)
n_groups <- function(x) {
  ifelse(x > 18, (x+3) %/% 4, x %/% 3)
}  

Roster <- readxl::read_excel("../grades/S23/Rosters-Spring2023.xlsx") |>
  rename(first = `Preferred First Name`) |>
  rename(last = `Last Name`) |>
  rename(email = `Primary Institutional Email Address`) |>
  rename(name = `Student`) |>
  rename(id = `Student ID`) |>
  separate(`Course Section`, into = c('course', 'section', 'title'), sep = "\\s*-\\s*", remove = FALSE) |>
  mutate(short_name = paste(first, substr(last, 1, 1))) |>
  filter(course == "MATH 252")


R <- 
  mosaic::shuffle(Roster) |>
  group_by(section) |>
  mutate(group = rep(1:(n_groups(n())), length.out = n())) |>
  mutate(group = paste0(section, group)) 
         
for(g in sort(unique(R$group))) {
  cat(paste0('  * Group ', g, ": ", paste(R %>% filter(group == g) %>% pull(short_name), collapse = ", "), "\n"))
}
```

::::

::::{.callout-note collapse="true"}
#### Groups starting 16 Jan

```{r echo = FALSE, results = "asis", include = TRUE, message = FALSE}
set.seed(116)
n_groups <- function(x) {
  ifelse(x > 18, (x+3) %/% 4, x %/% 3)
}  

Roster <- readxl::read_excel("../grades/S23/Rosters-Spring2023.xlsx") |>
  rename(first = `Preferred First Name`) |>
  rename(last = `Last Name`) |>
  rename(email = `Primary Institutional Email Address`) |>
  rename(name = `Student`) |>
  rename(id = `Student ID`) |>
  separate(`Course Section`, into = c('course', 'section', 'title'), sep = "\\s*-\\s*", remove = FALSE) |>
  mutate(short_name = paste(first, substr(last, 1, 1))) |>
  filter(course == "MATH 252")


R <- 
  mosaic::shuffle(Roster) |>
  group_by(section) |>
  mutate(group = rep(1:(n_groups(n())), length.out = n())) |>
  mutate(group = paste0(section, group)) 
         
for(g in sort(unique(R$group))) {
  cat(paste0('  * Group ', g, ": ", paste(R %>% filter(group == g) %>% pull(short_name), collapse = ", "), "\n"))
}
```

::::

::::{.callout-note collapse="true"}
#### Groups starting 25 Jan

```{r echo = FALSE, results = "asis", include = TRUE, message = FALSE}
set.seed(125)
n_groups <- function(x) {
  ifelse(x > 18, (x+3) %/% 4, x %/% 3)
}  

R <- 
  mosaic::shuffle(Roster) |>
  group_by(section) |>
  mutate(group = rep(1:(n_groups(n())), length.out = n())) |>
  mutate(group = paste0(section, group)) 
         
for(g in sort(unique(R$group))) {
  cat(paste0('  * Group ', g, ": ", paste(R %>% filter(group == g) %>% pull(short_name), collapse = ", "), "\n"))
}
```

::::


::::{.callout-note collapse="true"}
#### Groups starting 01 Feb

```{r echo = FALSE, results = "asis", include = TRUE, message = FALSE}
set.seed(201)
n_groups <- function(x) {
  ifelse(x > 18, (x+3) %/% 4, x %/% 3)
}  

R <- 
  mosaic::shuffle(Roster) |>
  group_by(section) |>
  mutate(group = rep(1:(n_groups(n())), length.out = n())) |>
  mutate(group = paste0(section, group)) 
         
for(g in sort(unique(R$group))) {
  cat(paste0('  * Group ', g, ": ", paste(R %>% filter(group == g) %>% pull(short_name), collapse = ", "), "\n"))
}
```
::::



### Graphs

```{block}
date     |  Topic                | link(s)
-------- | --------------------- | ------------------------------------------
Mon 1/9  | Intro to Graphs       | [PDF](/from-class/01-graphs.pdf)
Wed 1/11 | More Graphs           | [PDF](/from-class/02-graphs.pdf)
Wed 1/13 | Representing Graphs   | [PDF](/from-class/03-graphs.pdf)
Mon 1/16 | Graph Isomorphism     | [PDF](/from-class/04-graphs.pdf)
Wed 1/18 | Paths in Graphs       | [PDF](/from-class/05-graphs.pdf)
Fri 1/20 | Paths in Graphs       | [PDF](/from-class/05-graphs.pdf)
Mon 1/23 | Bipartite Graphs      | [PDF](/from-class/06-graphs.pdf)
Wed 1/25 | Planar Graphs         | [PDF](/from-class/07-graphs.pdf)
```

```{block}
#| include: true
### Counting and Probability

date     |  Topic                | link(s)
-------- | --------------------- | ------------------------------------------
Mon 1/30 | Some Counting Problems | [PDF](/from-class/08-counting.pdf)
Mon 1/30 | Some Counting Problems (solutions) | [PDF](/from-class/08-counting-sols.pdf)
Wed 2/01 | Pigeon Hole Principle | [PDF](/from-class/09-counting.pdf)
Fri 2/03 | Division Principle    | [PDF](/from-class/10-counting.pdf)
Mon 2/06 | Donuts                | [PDF](/from-class/11-counting.pdf)
```

:::


:::{.callout-note collapse="false"}
### Between Test 1 and Test 2

::::{.callout-note collapse="true"}
#### Groups starting 10 Feb

```{r echo = FALSE, results = "asis", include = TRUE, message = FALSE}
set.seed(210)
n_groups <- function(x) {
  ifelse(x > 18, (x+3) %/% 4, x %/% 3)
}  

R <- 
  mosaic::shuffle(Roster) |>
  group_by(section) |>
  mutate(group = rep(1:(n_groups(n())), length.out = n())) |>
  mutate(group = paste0(section, group)) 
         
for(g in sort(unique(R$group))) {
  cat(paste0('  * Group ', g, ": ", paste(R %>% filter(group == g) %>% pull(short_name), collapse = ", "), "\n"))
}
```
::::

```{block}
#| include: true
### Counting and Probability

date     |  Topic                | link(s)
-------- | --------------------- | ------------------------------------------
Fri 2/10 | Intro to Probability. | [PDF](/from-class/12-probability.pdf)
```

:::

:::
