---
title: ""
author: ""
date: ""
output: 
  html_document:
    includes:
      before_body: header.shtml
    css: ../styles/rpruim2017.css
---


<!-- Math 252 Spring 2020 -->

### Instructor

Randall Pruim  
office: North Hall 284   
phone: (616) 526-7113   
E-mail: [`rpruim@calvin.edu`](mailto:rpruim@calvin.edu)

### Time/Location

* **Section A:** Monday, Wednesday, Friday 11:30 - 12:20, in North Hall 259
* **Section B:** Monday, Wednesday, Friday 12:30 - 1:20, in North Hall 259


### Office Hours

Office hours will not be held in my office while we are online. But I will attempt to monitor
the MS Teams discussion more carefully from 11:30-1:30 Monday, Wednesday, and Friday (the usual
times of our class). So if you stick to that routine, you are likely to get the most rapid 
response both from me and from other students.

<!-- Official office hours are TBD, -->
<!-- but we can make arrangements for other times as well.  Catch me after -->
<!-- class, or send me an email with some times that work for you. -->
<!-- Or just stop by my office and see if I'm available. -->

## Course Objectives 

The student who successfully completes this class should be able to

1. Describe and analyze algorithms that use graphs.
2. Apply counting techniques to determine the size of finite sets and to compute probabilities (including conditional probabilities) of events.
3. Compute and interpret the mean and variance of a discrete random variable.
4. Identify problems that can and cannot be solved with various models of computation.

## Internet Resources

### Email

I will maintain an email list of all students registered in this class 
and will occasionally use it to distribute information and reminders of 
various things pertaining to this course. 
If you prefer to read your email from an account other than your Calvin 
student account and do not have it set up to forward automatically, 
send me email with the email address you prefer.

While we are online especially, please **check your email daily**.
You are responsible for any information communicated via email.

### MS Teams

At least while the class is online (and perhaps beyond), we will be using
**Microsoft Teams for class discussion**. Rather than emailing questions to me,
I encourage you to post your questions in the appropriate channel in MS Teams.
That way everyone can benefit from the answer.

You can also use MS Teams to message each other or to set up "meetings" where you 
can work online together.

<!-- ### Piazza -->

<!-- At least while the class is online (and perhaps beyond), we will be using -->
<!-- **Piazza for class discussion**. The system is highly catered to getting you -->
<!-- help fast and efficiently from classmates or instructors. Rather than emailing -->
<!-- questions to me, I encourage you to post your questions on Piazza. -->
<!-- Although I have only used Piazza a little bit, here are some of the advantages I see. -->

<!-- * It is used in some other CS courses, so some of you will be familiar with it -->
<!-- already, and others of you will use it in the future. It comes recommended by  -->
<!-- several instructors in CS. -->

<!-- * Conversations can be organized by themes.  -->

<!--     I've created a number of "folders" (they function more like tags than -->
<!--     folder), and you will need to select one for each new converstaion. This -->
<!--     will make it easier for all of us to find things and keep organized. -->

<!--     I've  created several "folders" already, include some that are targeted at -->
<!--     specific topics (like `probability-5`, which means things related to the -->
<!--     topic of worksheet 5, on probability). Let me know if you think I should add -->
<!--     some additional folders. -->

<!-- * The system that has been used the most by students (moodles discussion forums) -->
<!-- was rated pretty low in the survey. I took that to mean: "Please avoid." -->

<!-- * I've been told that the search mechanism works quite well -- that will make also help us find stuff. -->

<!-- * I can go in an mark responses as "approved" or "official", so you can know that a response -->
<!-- is good, even if it didn't originally come from me. -->

<!-- If you have any problems or feedback for the developers, email `team@piazza.com`. -->

<!-- Find our class page at: https://piazza.com/calvin/spring2020/math252/home or using -->
<!-- the quick link at the top of this page. -->

### Web Pages

In addition to this home page, 
I will also maintain a list of web resources pertaining to this course.
**You are responsible for any information appearing on the course web pages.**
Items I have prepared and maintain online include

* a [calendar](cal/) of daily topics, exams, etc.
* a list of [homework](hw/) assignments and due dates.
* information about [tests and exams](test-info/) (appearing shortly before each test date).

For quick access to these and other resources, see the navigation
bar at the top of this page.

## Other Important Information

### See me

If you are having difficulty with any portion of the course, 
do not hesitate to see me.
Do this as soon as possible, certainly well in advance of any
deadlines (like tests) so that we can work to fix the problem. 

### Textbook

The required text for this course is 
*Discrete Mathematics and Its Applications (7th edition)* by Ken Rosen.

###  Grading

Grading will be based on the following approximate weighting: 

* Homework, etc: 15%
* Tests: 60%
* Final Exam: 25%

### Tests 

Tests should be taken when they are scheduled.
I do not generally offer make-up, alternate or late tests. 
Instead, if you miss one test (for any reason) or if your final exam 
score is better than your worst test, then your final exam score will be
substituted for that test.

### Special Circumstances 

Occasionally there are special circumstances that require that the rules
and guidelines above be adjusted for a particular student. 
In such cases, it is the responsibility of the student to inform me 
of the situation **as soon as possible**, so that the appropriate
arrangements can be made.  This includes, but is not limited to, 
students with documented disabilities.


